name: 'Jest coverage report'
on:
    pull_request:
        branches:
            - main

jobs:
    coverage:

        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Install Dependencies
          run: npm install
      
        - name: Give jest write permission
          run: chmod +x node_modules/.bin/jest
  
        - name: Give jest-coverage-badges write permission
          run: chmod +x node_modules/.bin/jest-coverage-badges
  
        - name: Run tests and generate badges
          run: npm run badge